name: Cache Example Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Cache dependencies (example: Node modules)
      - name: Cache dependencies
        id: cache-node
        uses: actions/cache@v4
        with:
          path: ~/.npm          # or path to your dependencies
          key: cache-a555a00

      # Step to show cache hit/miss
      - name: prime-cache-a555a00
        run: |
          if [ -n "${{ steps.cache-node.outputs.cache-hit }}" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
